version: "3"

services:
  order-creator:
    container_name: order-creator
    image: gcr.io/zaidan-io/order-creator:latest
    environment:
      # Set WEB3_URL prior to deploying
      - WEB3_URL=
      - PORT=42001
      - DISABLE_SENDER=true
  
  order-poster:
    container_name: order-poster
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: ["order-creator"]
    environment:
      - ORDER_CREATOR_URL=http://order-creator:42001

      # Set MESH_RPC_URL and WEB3_URL prior to deploying
      - WEB3_URL=
      - MESH_RPC_URL=
      - MAKER_ADDRESS=
  
      # Change order duration (in seconds)
      - ORDER_DURATION_SECONDS=

      # default is ZRX (A) and TST (B) on the Ropsten network, change if needed
      - ASSET_A_ADDRESS=0xff67881f8d12f372d91baae9752eb3631ff0ed00
      - ASSET_B_ADDRESS=0x722dd3f80bac40c951b51bdd28dd19d435762180
